apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: stock-hanaro
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
spec:
  ingressClassName: traefik
  tls:
    - hosts: [stock.example.com]
      secretName: stock-hanaro-tls
  rules:
    - host: stock.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: stock-hanaro-frontend
                port: {number: 3000}
