apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: stock-hanaro
resources:
  - namespace.yaml
  - configmap.yaml
  - postgres.yaml
  - postgres-backup.yaml
  - backend.yaml
  - frontend.yaml
  - worker.yaml
  - migration.yaml
  - cronjobs.yaml
  - ingress.yaml
