apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - cluster-issuer.yaml
patches:
  - path: production-config.patch.yaml
  - path: production-ingress.patch.yaml
images:
  - name: stock-hanaro-backend
    newName: ghcr.io/OWNER/stock-hanaro-backend
    newTag: INITIAL_TAG
  - name: stock-hanaro-frontend
    newName: ghcr.io/OWNER/stock-hanaro-frontend
    newTag: INITIAL_TAG
